global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "web-scraper"
    static_configs:
      - targets: ["web-scraper:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "scheduler"
    static_configs:
      - targets: ["scheduler:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "dashboard"
    static_configs:
      - targets: ["dashboard:5000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]